### ISSUE TITLE
UpdateExistingRecord doesn't work

### ISSUE THREAD

**Issue by igroykt** [oze4/godaddygo#7]
Hello.
When I test example "UpdateExistingRecord" I get error:

> ErrorInvalidStatusCode : expected 200, got 422
> {"code":"MISSING_NAME_SERVER","message":"At least two NS records must be specified in the request body"}

And here is how looks "recordToUpdate":
```
recordToUpdate := godaddygo.Record{
		Name: "a1",
		Type: godaddygo.RecordTypeA,
		Data: "4.4.4.4",
		TTL: 3600,
	}
```

But I don't see any method to set NS servers. How to fix it?

Thank.

**Comment by oze4** [comment]
Apologies, I just saw this. Let me test and I'll get back to you. (may not be til tomorrow, though).

**Comment by oze4** [comment]
Just tested this.. I wonder if they updated something on their end? 

Either way I'll take a look in the morning.

**Comment by matthewoestreich** [comment]
Alright... I went ahead and got this semi-resolved.

I updated the example (which works) if you want to check it out : https://github.com/oze4/godaddygo/blob/master/examples/DNSRecords/UpdateExistingRecord/main.go
